# -*- coding: utf-8 -*-
"""spider data set.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U4ac3WwYd9u4kH4lIU3cfCkT6DdqrgWZ

โหลด DATA
"""

!pip install -q fastbook

from fastbook import *
from fastai.vision.widgets import *
from tqdm.auto import tqdm

!rm -r images

path = Path('images')

image_labels = [
'Phalangium opilio',
'Aphonopelma spp',
'Trochosa ruricola',
'Cheiracanthium spp',
'Nephila pilipes',
'Argiope pulchellla',
'Araneus  mitificus',
'Araneus diadematus',
'Zosis geniculata',
'Crossopriza lyoni',
'Oxyopes javanus',
'Menemerus bivittatus',
'Myrmaplata plataleoides',
'Sparassidae',
'Latrodectus geometricus',
'Latrodectus hasselti',
'Loxosceles reclusa',
'Loxosceles rufescens',
'Latrodectus hesperus',
]
#Taksinus bambus
MAX_N = 200

if not path.exists():
    path.mkdir()
    for o in tqdm(image_labels):
        dest = (path/o)
        dest.mkdir(exist_ok=True)
        results = search_images_ddg(o, max_images=MAX_N)
        download_images(dest, urls=results)

#เช็คว่าได้รูปอะไรบ้าง
fns = get_image_files(path)
fns



failed = verify_images(fns)
failed

#นำรูปที่หาไม่เจอออก
failed.map(Path.unlink)

#install fastai2
!pip install -Uqq fastbook wandb
import fastbook

from google.colab import drive
drive.mount("/content/drive/")

#imports 
from fastbook import *
from fastai.vision.widgets import *
from fastai.callback.wandb import WandbCallback
from fastai.callback.tracker import SaveModelCallback

import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from plotnine import *
import shutil
import wandb

import warnings
warnings.filterwarnings('ignore')

path = Path('/content/drive/MyDrive/images')

valid_Aphonopelma_spp = sorted(list((path/'/content/drive/MyDrive/images/train/Aphonopelma spp').glob('*')))
valid_Araneus_diadematus = sorted(list((path/'/content/drive/MyDrive/images/train/Araneus diadematus').glob('*')))
valid_Araneus_mitificus = sorted(list((path/'/content/drive/MyDrive/images/train/Araneus  mitificus').glob('*')))
valid_Argiope_pulchellla = sorted(list((path/'/content/drive/MyDrive/images/train/Argiope pulchellla').glob('*')))
valid_Cheiracanthium_spp = sorted(list((path/'/content/drive/MyDrive/images/train/Cheiracanthium spp').glob('*')))
valid_Crossopriza_lyoni = sorted(list((path/'/content/drive/MyDrive/images/train/Latrodectus geometricus').glob('*')))
valid_Latrodectus_geometricus = sorted(list((path/'/content/drive/MyDrive/images/train/Latrodectus geometricus').glob('*')))
valid_Latrodectus_hasselti = sorted(list((path/'/content/drive/MyDrive/images/train/Latrodectus hasselti').glob('*')))
valid_Latrodectus_hesperus = sorted(list((path/'/content/drive/MyDrive/images/train/Latrodectus hesperus').glob('*')))
valid_Loxosceles_reclusa = sorted(list((path/'/content/drive/MyDrive/images/train/Loxosceles reclusa').glob('*')))
valid_Loxosceles_rufescens = sorted(list((path/'/content/drive/MyDrive/images/train/Loxosceles rufescens').glob('*')))
valid_Menemerus_bivittatus = sorted(list((path/'/content/drive/MyDrive/images/train/Menemerus bivittatus').glob('*')))
valid_Myrmaplata_plataleoides = sorted(list((path/'/content/drive/MyDrive/images/train/Myrmaplata plataleoides').glob('*')))
valid_Nephila_pilipes = sorted(list((path/'/content/drive/MyDrive/images/train/Nephila pilipes').glob('*')))
valid_Oxyopes_javanus = sorted(list((path/'/content/drive/MyDrive/images/train/Oxyopes javanus').glob('*')))
valid_Phalangium_opilio = sorted(list((path/'/content/drive/MyDrive/images/train/Phalangium opilio').glob('*')))
valid_Sparassidae = sorted(list((path/'/content/drive/MyDrive/images/train/Sparassidae').glob('*')))
valid_Trochosa_ruricola = sorted(list((path/'/content/drive/MyDrive/images/train/Trochosa ruricola').glob('*')))
valid_Zosis_geniculata = sorted(list((path/'/content/drive/MyDrive/images/train/Zosis geniculata').glob('*')))

len(valid_Aphonopelma_spp)

np.random.seed(1412)
test_Aphonopelma_spp = np.random.choice(valid_Aphonopelma_spp,size=len(valid_Aphonopelma_spp)//2, replace=False)
test_Araneus_diadematusp = np.random.choice(valid_Araneus_diadematus, size=len(valid_Araneus_diadematus)//2, replace=False)
test_Araneus_mitificus = np.random.choice(valid_Araneus_mitificus, size=len(valid_Araneus_mitificus)//2, replace=False)
test_Argiope_pulchellla = np.random.choice(valid_Argiope_pulchellla, size=len(valid_Argiope_pulchellla)//2, replace=False)
test_Cheiracanthium_spp = np.random.choice(valid_Cheiracanthium_spp, size=len(valid_Cheiracanthium_spp)//2, replace=False)
test_Crossopriza_lyoni = np.random.choice(valid_Crossopriza_lyoni, size=len(valid_Crossopriza_lyoni)//2, replace=False)
#test_Latrodectus_geometricus = np.random.choice(valid_Latrodectus_geometricus, size=len(valid_Latrodectus_geometricus)//2, replace=False)
test_Latrodectus_hasselti = np.random.choice(valid_Latrodectus_hasselti, size=len(valid_Latrodectus_hasselti)//2, replace=False)
test_Latrodectus_hesperus = np.random.choice(valid_Latrodectus_hesperus, size=len(valid_Latrodectus_hesperus)//2, replace=False)
test_Loxosceles_reclusa = np.random.choice(valid_Loxosceles_reclusa, size=len(valid_Loxosceles_reclusa)//2, replace=False)
test_Loxosceles_rufescens = np.random.choice(valid_Loxosceles_rufescens, size=len(valid_Loxosceles_rufescens)//2, replace=False)
test_Menemerus_bivittatus = np.random.choice(valid_Menemerus_bivittatus, size=len(valid_Menemerus_bivittatus)//2, replace=False)
test_Myrmaplata_plataleoides  = np.random.choice(valid_Myrmaplata_plataleoides, size=len(valid_Myrmaplata_plataleoides)//2, replace=False)
test_Nephila_pilipes = np.random.choice(valid_Nephila_pilipes, size=len(valid_Nephila_pilipes)//2, replace=False)
test_Oxyopes_javanus = np.random.choice(valid_Oxyopes_javanus, size=len(valid_Oxyopes_javanus)//2, replace=False)
test_Phalangium_opilio = np.random.choice(valid_Phalangium_opilio , size=len(valid_Phalangium_opilio )//2, replace=False)
test_Sparassidae = np.random.choice(valid_Sparassidae, size=len(valid_Sparassidae)//2, replace=False)
test_Trochosa_ruricola = np.random.choice(valid_Trochosa_ruricola, size=len(valid_Trochosa_ruricola)//2, replace=False)
test_Zosis_geniculata = np.random.choice(valid_Zosis_geniculata, size=len(valid_Zosis_geniculata)//2, replace=False)

for fname in test_Aphonopelma_spp :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Aphonopelma spp')
for fname in test_Araneus_diadematusp  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Araneus_diadematus')
for fname in test_Araneus_mitificus  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Araneus_mitificus')   
for fname in test_Argiope_pulchellla  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Argiope_pulchellla')
for fname in test_Cheiracanthium_spp  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Cheiracanthium_spp')
for fname in test_Crossopriza_lyoni  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Crossopriza_lyoni')

for fname in test_Latrodectus_hasselti  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Latrodectus_hasselti') 
for fname in test_Latrodectus_hesperus  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Latrodectus_hesperus') 
for fname in test_Loxosceles_reclusa :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Loxosceles_reclusa') 
for fname in test_Loxosceles_rufescens  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Loxosceles_rufescens') 
for fname in test_Menemerus_bivittatus  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Menemerus_bivittatus')
for fname in test_Myrmaplata_plataleoides  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Myrmaplata_plataleoides') 
for fname in test_Nephila_pilipes  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Nephila_pilipes')                            
for fname in test_Oxyopes_javanus  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Oxyopes_javanus')
for fname in test_Phalangium_opilio  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Phalangium_opilio')
for fname in test_Sparassidae  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Sparassidae')            
for fname in test_Trochosa_ruricola  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Trochosa_ruricola')
for fname in test_Zosis_geniculata  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Zosis_geniculata')

for fname in test_Latrodectus_geometricus  :
    shutil.move(str(fname),'/content/drive/MyDrive/images/test/test_Latrodectus_geometricus')